name: Backend CI

on:
  push:
    paths:
      - "**/*.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "**/*.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/backend-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json  # << root lockfile

      - name: Install
        run: npm ci

      - name: Run tests
        env:
          NODE_ENV: test
          WORDSAPI_KEY: dummy
        run: npm run test:ci
        
