# This workflow runs unit tests for the Node.js backend.
name: Node.js CI

# Triggers the workflow on pushes to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Use the latest Ubuntu runner hosted by GitHub
    runs-on: ubuntu-latest

    # Set up the execution environment
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Configure Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recommended stable Node.js version

      # Install dependencies, but first, force a stable Jest version to fix the 'replaceAll' error
      - name: Install dependencies (npm ci and stable Jest)
        run: |
          npm ci
          # Override the potentially problematic version with a known stable version of Jest (v29)
          npm install --save-dev jest@29.7.0

      # Configure Jest (use jest.config.js for maximum compatibility with forced version)
      - name: Configure Jest for CommonJS (CJS) tests
        run: |
          # Use jest.config.js to allow CJS syntax in the config file
          echo "module.exports = { testEnvironment: 'node' };" > jest.config.js

      # Run the automated unit tests
      - name: Run tests (npm test)
        # This command runs the script defined in package.json: "test": "jest"
        run: npm test
