# This workflow runs unit tests for the Node.js backend.
name: Node.js CI

# Triggers the workflow on pushes to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Use the latest Ubuntu runner hosted by GitHub
    runs-on: ubuntu-latest

    # Set up the execution environment
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Configure Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recommended stable Node.js version

      # --- FIX: Enforce stable Jest version to resolve internal 'replaceAll' error ---
      - name: Install dependencies and stable Jest
        run: |
          # Use npm install instead of npm ci for a cleaner install path
          npm install
          # Explicitly install Jest 29.7.0, which is known to be stable and does not have the internal 'replaceAll' bug
          npm install --save-dev jest@29.7.0

      # Configure Jest Environment
      - name: Configure Test Environment
        run: |
          # Create a simple config file to set the environment
          echo "module.exports = { testEnvironment: 'node' };" > jest.config.js

      # Run the automated unit tests
      - name: Run tests (npm test)
        run: npm test
