name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Use a fresh Ubuntu runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Use Node 20 as specified in your setup
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies and explicitly set Jest version
        run: |
          # Install all dependencies based on package-lock.json
          npm install
          
          # CRITICAL FIX: Explicitly downgrade Jest to a stable version (29.7.0)
          # Jest 30.x has internal dependencies that throw errors (e.g., 'replaceAll is not a function') 
          # due to environment compatibility issues on some runners. 
          # Forcing 29.7.0 fixes this specific runtime problem.
          echo "Forcing Jest downgrade to 29.7.0 to fix internal dependency errors."
          npm install --save-dev jest@29.7.0 --force

      - name: Run tests
        # This step will now use Jest 29.7.0, which was explicitly installed in the previous step
        run: npm test
